### ISSUE TITLE
[1.12.2 - 0.6.0.40 BETA 1] Server crash on startup with only Matter Overdrive and CLib.

### ISSUE THREAD

**Issue by DenisMasterHerobrine** [MatterOverdrive/MatterOverdrive-Legacy-Edition#34] opened 2018-02-13 19:29 UTC
**Forge version:  14.23.2.2615**
**Minecraft version: 1.12.2**
**CLib version: 1.0.2.31**
**Matter Overdrive version: 0.6.0.40 BETA 1**
**Crashlogs & Logs:**
[`Crash Log`](https://pastebin.com/MLB98gRF)
[`Earlystartup Log`](https://pastebin.com/E1UuHFuQ)
[`FML-Server-Latest Log`](https://pastebin.com/Y948p1Py)

Wanted to play with friends with mods and Matter Overdrive, server has been crashed after a seconds, when started. Seems, Matter Overdrive tried to load CommonProxy, but something goes wrong and it crashing a server.

**Comment by adrwa** [comment] 2018-02-13 19:30
duplicate of #33

**Closed as completed by adrwa** 2018-02-13 19:30 UTC
Labels: resolved: duplicate

**Comment by DenisMasterHerobrine** [comment] 2018-02-13 19:31
Oops. Sorry, for duplicating.

**Comment by adrwa** [comment] 2018-02-13 19:31
its not a problem, i can understand duplicates when the other issue is closed
