### ISSUE TITLE
Having a really hard time making a network

### ISSUE THREAD

**Issue by Ziriel2002** [MatterOverdrive/MatterOverdrive-Legacy-Edition#125] opened 2018-05-05 21:50 UTC
#### Issue Description:
matter network not working.

#### What happens:
i dont know whats happening. Ive been trying to make a network for 2 hours now, doing what the datapad and website and videos say but its not working. idk if Im doing something wrong or something but it wont work no matter what I do. I put pattern drives into the pattern holder and the screen shows 0 patterns even though its connected

i also tried copying other matter networks for people who built working ones and even from the data pad and your website but it still doesnt work for me
![2018-05-05_16 46 16](https://user-images.githubusercontent.com/39014651/39667830-1b7daf94-5084-11e8-83f5-b71011c32c89.png)

#### What you expected to happen:
the matter network to work

#### How to reproduce:
try building a matter network

#### Affected Versions (Do *not* use "*latest*"):

 - CLib: 1.0.2.31
 - MatterOverdrive: 1.12.2-0.6.0.148
 - Forge: 14.23.2.2611
 - Minecraft: 1.12.2

#### Crash report, if relevent
none

**Comment by adrwa** [comment] 2018-05-05 21:52
duplicate of #84

**Closed as completed by adrwa** 2018-05-05 21:52 UTC
Labels: resolved: duplicate

**Comment by Ziriel2002** [comment] 2018-05-05 22:06
fast response but is there anyway i can fix it? this is happening on the latest dev builds for me to
