### ISSUE TITLE
Crash generating mad scientist in village

### ISSUE THREAD

**Issue by evhub** [MatterOverdrive/MatterOverdrive-Legacy-Edition#120] opened 2018-04-16 00:27 UTC
See crash report [here](https://gist.github.com/evhub/7f00cf10615687c134b057f2c41918b8). Traceback seems to suggest a matter overdrive issue, but I also see recurrent complex, biomes o plenty, and forestry showing up there, so it's possible this is an issue with one of those mods instead. In that case, feel free to close this issue.

**Comment by adrwa** [comment] 2018-04-16 00:28
Duplicate of #112

**Closed as completed by adrwa** 2018-04-16 00:28 UTC
Labels: resolved: duplicate
