### ISSUE TITLE
crash game when I tried to install an energy cell from a mod mekanism

### ISSUE THREAD

**Issue by KiraLinux** [MatterOverdrive/MatterOverdrive-Legacy-Edition#43] opened 2018-02-14 21:55 UTC
I tried to install an energy cell in one of the weapons in the weapons table

crash logs in the archive
[crash-2018-02-15_00.48.00-client.zip](https://github.com/MatterOverdrive/MatterOverdrive/files/1725778/crash-2018-02-15_00.48.00-client.zip)

**Comment by adrwa** [comment] 2018-02-14 21:57
duplicate of #26

**Closed as completed by adrwa** 2018-02-14 21:57 UTC
Labels: resolved: duplicate
