### ISSUE TITLE
[1.12.2] Ticking World Exception (Mad Scientist)

### ISSUE THREAD

**Issue by Deloyar81** [MatterOverdrive/MatterOverdrive-Legacy-Edition#119] opened 2018-04-15 19:46 UTC
By generating and populating a new chunk, the client crash. I have not the time yet to reproduce  this issue on my server, but I will test it tomorrow.

The crash-log intends, that it has something to do with the "lost cities" world generation, but I'm not sure, if this is a coinicidence or not, 'cause I can't reproduce the issue in vanilla, BOP, etc. yet.

[Pastebin](https://pastebin.com/rLtkPu1V)

291 Mods loaded
Forge 14.23.2.2654
Matter Overdrive 0.6.0.144
CLib 1.0.2.31
Lost Citites 1.12-2.0.5

**Comment by adrwa** [comment] 2018-04-15 19:47
Duplicate of #112

**Closed as completed** 2018-04-15 19:46 UTC
Labels: resolved: duplicate
