### ISSUE TITLE
Mater Pipe Bug

### ISSUE THREAD

**Issue by MarkoZ7** [MatterOverdrive/MatterOverdrive-Legacy-Edition#155] opened 2018-07-01 11:27 UTC
#### Issue Description:
When i put two or more Matter Transport Pipe or Heavy Duty Matter Transport Pipe one to each other they are not connected and they are not transporting matter, but this bug does not affect Matter Network Cable.

![screenshot001](https://user-images.githubusercontent.com/40733843/42133865-409b68aa-7d31-11e8-8d8e-a3d75c74c76c.jpg)

#### How to reproduce:
Just take two Matter Transport Pipe and put them one to each other.

#### Affected Versions (Do *not* use "*latest*"):

- MatterOverdrive: 0.6.0.176
- Forge: 14.23.4.2705
- Minecraft: 1.12.2

**Comment by adrwa** [comment] 2018-07-01 11:34
Duplicate of #20

**Closed as completed** 2018-07-01 11:35 UTC
Labels: resolved: duplicate
