### ISSUE TITLE
Crash while analyzing CobbelStone

### ISSUE THREAD

**Issue by TobsenD** [MatterOverdrive/MatterOverdrive-Legacy-Edition#113] opened 2018-04-05 18:44 UTC
Minecraft Server crashes when the Matter Analyzer finishes analyzing CobbelStone.
Crashlog: https://pastebin.com/mZXkVg7y

**Comment by adrwa** [comment] 2018-04-05 18:47
Duplicate of #97

**Closed as completed by adrwa** 2018-04-05 18:47 UTC
Labels: resolved: duplicate, resolved: invalid
