### ISSUE TITLE
[1.12] Duplicate stat id (Crash on start)

### ISSUE THREAD

**Issue by MasterEnderman** [MatterOverdrive/MatterOverdrive-Legacy-Edition#87] opened 2018-03-01 22:34 UTC
Matter Overdrive: 0.6.0.108
Forge: 14.23.2.2623
Crash Report: https://pastebin.com/zqCdzfsU

**Comment by adrwa** [comment] 2018-03-01 22:54
duplicate of #83

**Closed as completed by adrwa** 2018-03-01 22:54 UTC
Labels: resolved: invalid
