### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Nexusdog** [MatterOverdrive/MatterOverdrive-Legacy-Edition#114] opened 2018-04-05 23:59 UTC
MC/F 1.12.2/2654
MatterOverdrive-1.12.2-0.6.0.144-universal

Doesn't seem to like working with forestry_1.12.2-5.8.0.262 maybe...???

https://pastebin.com/w6AgN2Va

**Comment by adrwa** [comment] 2018-04-06 16:17
Duplicate of #112

**Closed as completed** 2018-04-06 16:17 UTC
Labels: resolved: duplicate
